<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE squad [
 <!ELEMENT squad (name, email, web, picture, title, member+)>
 <!ATTLIST squad nick CDATA #REQUIRED>
 <!ELEMENT web (#PCDATA)>
 <!ELEMENT picture (#PCDATA)>
 <!ELEMENT title (#PCDATA)>
 <!ELEMENT member (name, email, icq, remark)>
 <!ATTLIST member id CDATA #REQUIRED nick CDATA #REQUIRED>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT email (#PCDATA)>
 <!ELEMENT icq (#PCDATA)>
 <!ELEMENT remark (#PCDATA)>]>
<squad nick="] [">
 <name></name>
 <email></email>
 <web></web>
 <picture>skull.paa</picture>
 <title></title>
 <member id="3469487" nick="Poweruser">
  <name>Poweruser</name>
  <email>poweruser.rs@hotmail.com</email>
  <icq>222909379</icq>
  <remark>I'm using the power! And what do you do?</remark>
 </member>
</squad>